export const SCOUTING_FACTS = [
  "Scouting America has over 2 million youth members worldwide.",
  "Scouting was founded in 1907 by Robert Baden-Powell in England.",
  "Eagle Scout is the highest rank in Scouting for boys.",
  "Merit badges help Scouts explore their interests and develop skills.",
  "The Scout Oath is a commitment to honor, integrity, and service.",
  "Scouting teaches outdoor survival skills and wilderness appreciation.",
  "Many famous people were Eagle Scouts, including Neil Armstrong.",
  "The Scout Motto is 'Be Prepared' - always ready for any challenge.",
  "Camping and backpacking are core outdoor activities in Scouting.",
  "Scouts learn leadership by taking on roles in their patrols.",
  "First aid is an essential skill taught in every Scouting rank.",
  "Environmental conservation is a core value of Scouting.",
  "Scouts participate in community service projects throughout the year.",
  "Scouting develops character and citizenship in young people.",
  "The Scout Salute is a sign of respect and unity among Scouts.",
  "Scouting has a 115+ year history of youth development.",
  "Scouts learn to work together as a team in their patrol.",
  "Knot-tying is a practical skill every Scout masters.",
  "Scouting provides opportunities to explore careers and interests.",
  "The campfire is a central gathering place for Scouts.",
  "Scouts learn navigation skills including map reading and compass use.",
  "Hiking and backpacking develop physical fitness and endurance.",
  "Swimming is an important water safety skill in Scouting.",
  "Scouts learn to start and manage campfires safely.",
  "Scouting teaches cooking skills and outdoor meal preparation.",
  "Scouts respect nature and leave no trace when camping.",
  "Troop meetings build friendships and a sense of brotherhood.",
  "Scouts participate in court of honor ceremonies to recognize achievements.",
  "The Scout uniform represents pride in Scouting traditions.",
  "Scouts learn first responder skills including CPR and rescue techniques.",
  "Nature observation and wildlife identification are Scout skills.",
  "Scouts explore science through outdoor activities and badge work.",
  "Pioneering teaches rope work and outdoor construction skills.",
  "Scouts learn rock climbing and rappelling safely with equipment.",
  "Water activities include kayaking, canoeing, and sailing.",
  "Scouting emphasizes physical fitness and healthy outdoor living.",
  "Scouts learn to identify edible plants and understand foraging.",
  "Environmental stewardship projects help preserve natural areas.",
  "Scouts participate in service learning projects in their communities.",
  "The patrol system teaches boys to support and help each other.",
  "Scouts develop public speaking and communication skills.",
  "Scouting teaches financial literacy and money management.",
  "Scouts explore technology including digital photography and coding.",
  "Astronomy merit badge teaches Scout to observe the night sky.",
  "Scouts learn about sustainable living and environmental conservation.",
  "Troop leadership positions prepare Scouts for future leadership roles.",
  "Scouts participate in large gatherings including Jamborees.",
  "Scouting teaches conflict resolution and problem-solving skills.",
  "Scouts learn to respect diversity and work with people from all backgrounds.",
  "Scouting emphasizes integrity, honesty, and ethical behavior.",
  "Board of Review evaluates Scout progress and rank advancement.",
  "Scouts earn merit badges by meeting specific skill requirements.",
  "Scouting history includes participation in major historical events.",
  "Scouts learn wilderness first aid and emergency procedures.",
  "The Scout Law guides ethical behavior and decision-making.",
  "Scouts participate in flag ceremonies and patriotic events.",
  "Scouting develops resilience and ability to overcome challenges.",
  "Scouts learn to plan and organize camping trips and outings.",
  "Scouting teaches respect for authority and following safety guidelines.",
  "Scouts explore artistic expression through various creative activities.",
  "Scouting provides mentorship from experienced adult leaders.",
  "Scouts learn about different cultures through badge work and activities.",
  "Scouting emphasizes helping others and service to community.",
  "Scouts participate in peer mentoring and teaching younger members.",
  "Scouting develops self-confidence and personal growth.",
  "Scouts learn water safety including proper swimming techniques.",
  "Scouting teaches fire safety and burn prevention.",
  "Scouts explore music and performance arts through badge work.",
  "Scouting provides opportunities for international travel and cultural exchange.",
  "Scouts learn about local history and heritage through projects.",
  "Scouting teaches emergency preparedness and disaster response.",
  "Scouts develop time management and organizational skills.",
  "Scouting provides challenges that build physical and mental toughness.",
  "Scouts learn to respect the environment and practice Leave No Trace.",
  "Scouting emphasizes cooperation over competition.",
  "Scouts explore STEM subjects through engaging activities.",
  "Scouting teaches critical thinking and problem-solving.",
  "Scouts participate in ritual and ceremony that connect them to tradition.",
  "Scouting develops compassion and empathy for others.",
  "Scouts learn about health, nutrition, and fitness.",
  "Scouting provides safe, structured fun and adventure.",
  "Scouts explore careers through vocational merit badges.",
  "Scouting teaches personal finance and budgeting.",
  "Scouts participate in outdoor cooking challenges and competitions.",
  "Scouting develops technical skills and hands-on competency.",
  "Scouts learn about different faith traditions and respect beliefs.",
  "Scouting teaches media literacy and digital citizenship.",
  "Scouts explore entrepreneurship and business skills.",
  "Scouting provides role models through experienced leaders.",
  "Scouts participate in advancement boards that celebrate progress.",
  "Scouting teaches safety awareness and risk management.",
  "Scouts develop communication skills through public speaking events.",
  "Scouting explores trades and skilled labor opportunities.",
  "Scouts learn about local government and civic responsibility.",
  "Scouting emphasizes the importance of family connections.",
  "Scouts participate in international Scouting events and exchanges.",
  "Scouting teaches environmental education and conservation skills.",
  "Scouts develop leadership through taking on responsibility.",
  "Scouting provides structure and positive peer relationships.",
  "Scouts explore art, music, and cultural expression.",
  "Scouting teaches respect for property and resources.",
  "Scouts participate in mentoring and peer teaching.",
  "Scouting develops decision-making skills and judgment.",
  "Scouts learn about different occupations through exploration.",
  "Scouting provides opportunities to give back to the community.",
  "Scouts develop perseverance and determination.",
  "Scouting teaches respect for authority and constructive criticism.",
  "Scouts explore different religions and spiritual traditions.",
  "Scouting develops social skills and friendship building.",
  "Scouts learn outdoor navigation and orienteering skills.",
  "Scouting provides safe spaces to take risks and learn.",
  "Scouts participate in team challenges and group activities.",
  "Scouting teaches planning and preparation for outdoor adventures.",
  "Scouts develop self-reliance and independence.",
  "Scouting emphasizes helping others without expecting reward.",
  "Scouts explore STEM careers and opportunities.",
  "Scouting teaches weather awareness and adaptation skills.",
  "Scouts participate in ceremonies that honor achievements.",
  "Scouting develops courage and willingness to try new things.",
  "Scouts learn about conservation and protecting natural resources.",
  "Scouting provides positive role models and mentors.",
  "Scouts participate in community service and humanitarian work.",
  "Scouting teaches respect for different perspectives and opinions.",
  "Scouts develop teamwork and collaboration skills.",
  "Scouting explores creative expression through various arts.",
  "Scouts learn survival skills and outdoor self-sufficiency.",
  "Scouting provides structure and positive adult supervision.",
  "Scouts participate in advancement and celebrate milestones.",
  "Scouting develops critical thinking and analytical skills.",
  "Scouts learn about different cultures and traditions.",
  "Scouting emphasizes personal responsibility and accountability.",
  "Scouts explore different career paths and opportunities.",
  "Scouting teaches respect for the rule of law.",
  "Scouts develop communication and interpersonal skills.",
  "Scouting provides safe outdoor recreation and adventure.",
  "Scouts participate in peer support and mentoring.",
  "Scouting develops resilience and coping skills.",
  "Scouts learn about local and global environmental issues.",
  "Scouting teaches respect for different family structures.",
  "Scouts participate in meaningful community projects.",
  "Scouting develops leadership potential in every Scout.",
  "Scouts learn outdoor cooking and food safety.",
  "Scouting provides opportunities for spiritual growth.",
  "Scouts explore different interests through merit badges.",
  "Scouting teaches respect for diversity and inclusion.",
  "Scouts develop independence and critical thinking.",
  "Scouting emphasizes service to others and community.",
];
